default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - commit-msg

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        name: check conventional commits
        stages: [ commit-msg ]
        args: [--strict]

  - repo: local
    hooks:
      - id: lint
        name: check and fix linting issues
        entry: make lint
        language: system
        pass_filenames: false

      - id: test
        name: run tests
        entry: make test
        language: system
        pass_filenames: false
