{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "StreamList ",
   "type": "timeseries",
   "description": "req: The number of messages received per RPC.\n\nresp: The number of messages sent per RPC",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(increase(rpc_client_requests_per_rpc_count{}[$__rate_interval])) by (rpc_grpc_status_code, rpc_method)",
     "legendFormat": "req {{rpc_grpc_status_code}} "
    },
    {
     "expr": "sum(increase(rpc_client_responses_per_rpc_count{}[$__rate_interval])) by (rpc_grpc_status_code, rpc_method)",
     "legendFormat": "resp {{rpc_grpc_status_code}} "
    }
   ]
  },
  {
   "title": "StreamList Latency",
   "type": "timeseries",
   "description": "The duration of outbound RPC.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rpc_client_duration_milliseconds_bucket{exported_job=\"reader-worker\", rpc_grpc_status_code=\"0\"}[$__rate_interval])) by (le, rpc_method))",
     "legendFormat": "95h"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rpc_client_duration_milliseconds_bucket{exported_job=\"reader-worker\", rpc_grpc_status_code=\"0\"}[$__rate_interval])) by (le, rpc_method))",
     "legendFormat": "50h"
    },
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_sum{exported_job=\"reader-worker\", rpc_grpc_status_code=\"0\"}[$__rate_interval]))\n/\nsum(rate(rpc_client_duration_milliseconds_count{exported_job=\"reader-worker\", rpc_grpc_status_code=\"0\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Count of live goroutines.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "avg_over_time(go_goroutine_count{exported_job=~\"reader-consumer|finder|reader-worker\"}[$__rate_interval])",
       "legendFormat": "{{exported_job}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Memory used by the Go runtime.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(go_memory_used_bytes{exported_job=~\"reader-consumer|reader-worker\"}) by (exported_job, go_memory_type)",
       "legendFormat": "{{exported_job}} {{go_memory_type}}"
      }
     ]
    }
   ]
  }
 ]
}