apiVersion: v1
kind: Secret
metadata:
  name: common
  namespace: youtube
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-0.replica-set.mongo.svc.cluster.local:27017,mongodb-1.replica-set.mongo.svc.cluster.local:27017,mongodb-2.replica-set.mongo.svc.cluster.local:27017/admin?replicaSet=rs0"
