// Code generated by MockGen. DO NOT EDIT.
// Source: live.go
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=kafka_test -source=live.go
//

// Package kafka_test is a generated GoMock package.
package kafka_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/natsoman/youtube-chat-reader/apps/reader/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLiveStreamProgressRepository is a mock of LiveStreamProgressRepository interface.
type MockLiveStreamProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLiveStreamProgressRepositoryMockRecorder
	isgomock struct{}
}

// MockLiveStreamProgressRepositoryMockRecorder is the mock recorder for MockLiveStreamProgressRepository.
type MockLiveStreamProgressRepositoryMockRecorder struct {
	mock *MockLiveStreamProgressRepository
}

// NewMockLiveStreamProgressRepository creates a new mock instance.
func NewMockLiveStreamProgressRepository(ctrl *gomock.Controller) *MockLiveStreamProgressRepository {
	mock := &MockLiveStreamProgressRepository{ctrl: ctrl}
	mock.recorder = &MockLiveStreamProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveStreamProgressRepository) EXPECT() *MockLiveStreamProgressRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockLiveStreamProgressRepository) Insert(ctx context.Context, lsp *domain.LiveStreamProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, lsp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockLiveStreamProgressRepositoryMockRecorder) Insert(ctx, lsp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLiveStreamProgressRepository)(nil).Insert), ctx, lsp)
}
