apiVersion: v1
kind: Service
metadata:
  name: replica-set
  namespace: mongo
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
