apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
  labels:
    app: mongodb
spec:
  serviceName: replica-set
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0.15
        ports:
        - containerPort: 27017
        command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - rs0
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
